// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{bitflags::bitflags,translate::*};

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "BablModelFlag")]
    pub struct ModelFlag: u32 {
        #[doc(alias = "BABL_MODEL_FLAG_ALPHA")]
        const ALPHA = ffi::BABL_MODEL_FLAG_ALPHA as _;
        #[doc(alias = "BABL_MODEL_FLAG_ASSOCIATED")]
        const ASSOCIATED = ffi::BABL_MODEL_FLAG_ASSOCIATED as _;
        #[doc(alias = "BABL_MODEL_FLAG_INVERTED")]
        const INVERTED = ffi::BABL_MODEL_FLAG_INVERTED as _;
        #[doc(alias = "BABL_MODEL_FLAG_LINEAR")]
        const LINEAR = ffi::BABL_MODEL_FLAG_LINEAR as _;
        #[doc(alias = "BABL_MODEL_FLAG_NONLINEAR")]
        const NONLINEAR = ffi::BABL_MODEL_FLAG_NONLINEAR as _;
        #[doc(alias = "BABL_MODEL_FLAG_PERCEPTUAL")]
        const PERCEPTUAL = ffi::BABL_MODEL_FLAG_PERCEPTUAL as _;
        #[doc(alias = "BABL_MODEL_FLAG_GRAY")]
        const GRAY = ffi::BABL_MODEL_FLAG_GRAY as _;
        #[doc(alias = "BABL_MODEL_FLAG_RGB")]
        const RGB = ffi::BABL_MODEL_FLAG_RGB as _;
        #[doc(alias = "BABL_MODEL_FLAG_CIE")]
        const CIE = ffi::BABL_MODEL_FLAG_CIE as _;
        #[doc(alias = "BABL_MODEL_FLAG_CMYK")]
        const CMYK = ffi::BABL_MODEL_FLAG_CMYK as _;
    }
}

#[doc(hidden)]
impl IntoGlib for ModelFlag {
    type GlibType = ffi::BablModelFlag;

    #[inline]
    fn into_glib(self) -> ffi::BablModelFlag {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::BablModelFlag> for ModelFlag {
    #[inline]
    unsafe fn from_glib(value: ffi::BablModelFlag) -> Self {
        skip_assert_initialized!();
        Self::from_bits_truncate(value)
    }
}

