// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../..
// from ../../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT(BABL_ALPHA_FLOOR);
    PRINT_CONSTANT(BABL_ALPHA_FLOOR_F);
    PRINT_CONSTANT((gint) BABL_ICC_INTENT_ABSOLUTE_COLORIMETRIC);
    PRINT_CONSTANT((gint) BABL_ICC_INTENT_PERCEPTUAL);
    PRINT_CONSTANT((gint) BABL_ICC_INTENT_PERFORMANCE);
    PRINT_CONSTANT((gint) BABL_ICC_INTENT_RELATIVE_COLORIMETRIC);
    PRINT_CONSTANT((gint) BABL_ICC_INTENT_SATURATION);
    PRINT_CONSTANT(BABL_MAJOR_VERSION);
    PRINT_CONSTANT(BABL_MICRO_VERSION);
    PRINT_CONSTANT(BABL_MINOR_VERSION);
    PRINT_CONSTANT((guint) BABL_MODEL_FLAG_ALPHA);
    PRINT_CONSTANT((guint) BABL_MODEL_FLAG_ASSOCIATED);
    PRINT_CONSTANT((guint) BABL_MODEL_FLAG_CIE);
    PRINT_CONSTANT((guint) BABL_MODEL_FLAG_CMYK);
    PRINT_CONSTANT((guint) BABL_MODEL_FLAG_GRAY);
    PRINT_CONSTANT((guint) BABL_MODEL_FLAG_INVERTED);
    PRINT_CONSTANT((guint) BABL_MODEL_FLAG_LINEAR);
    PRINT_CONSTANT((guint) BABL_MODEL_FLAG_NONLINEAR);
    PRINT_CONSTANT((guint) BABL_MODEL_FLAG_PERCEPTUAL);
    PRINT_CONSTANT((guint) BABL_MODEL_FLAG_RGB);
    PRINT_CONSTANT((gint) BABL_SPACE_FLAG_EQUALIZE);
    PRINT_CONSTANT((gint) BABL_SPACE_FLAG_NONE);
    return 0;
}
