// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../..
// from ../../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "BablIccIntent", sizeof(BablIccIntent), alignof(BablIccIntent));
    printf("%s;%zu;%zu\n", "BablModelFlag", sizeof(BablModelFlag), alignof(BablModelFlag));
    printf("%s;%zu;%zu\n", "BablSpaceFlags", sizeof(BablSpaceFlags), alignof(BablSpaceFlags));
    return 0;
}
